@extends('layouts.app')
@section('title', __('ui.farm_overview'))
@section('subtitle', __('ui.closer_connection'))
@section('content')
@if($notice)<div class="notice">{{ $notice }}</div>@endif
<section class="farm-banner"><div><span class="eyebrow">{{ __('ui.farm_connected') }}</span><h2>{{ __('ui.hello', ['name' => explode(' ', auth()->user()->name)[0]]) }}</h2><p>{{ __('ui.keep_crops_in_view') }}</p>@can('create', \App\Models\Crop::class)<a href="{{ route('crops.create') }}" class="agri-btn harvest-button"><i data-lucide="plus"></i>{{ __('ui.add_crop') }}</a>@endcan</div><div class="banner-stats"><div><strong>{{ $cropCount }}</strong><span>{{ __('ui.growing_spaces') }}</span></div><div><strong data-active-devices>{{ $activeDevices }}</strong><span>{{ __('ui.devices_online') }}</span></div><div><strong>{{ $alertsCount }}</strong><span>{{ __('ui.active_alerts') }}</span></div></div></section>
<div class="section-heading mt-7"><div><h2>{{ __('ui.latest_field_conditions') }}</h2><p class="muted text-sm">{{ $latestReading?->crop?->name ?? __('ui.connect_device_to_begin') }} @if($latestReading) · {{ __('ui.observed_at') }} {{ $latestReading->reading_at->translatedFormat('d M, H:i') }} @endif</p></div><a href="{{ route('monitoring.index') }}" class="text-link">{{ __('navigation.monitoring') }} <i data-lucide="arrow-up-right"></i></a></div>
<div class="sensor-grid" @if($sensorDevice) data-sensor-live="{{ route('monitoring.latest', ['device_id' => $sensorDevice->id]) }}" @endif>@foreach(config('agrisense.sensors') as $key=>$meta)<x-sensor-card :sensor="$key" :reading="$latestReading" />@endforeach</div>
@if($sensorDevice)<p class="muted text-xs" data-sensor-update role="status">{{ $latestReading?->reading_at?->diffForHumans() ?? 'Waiting for a Supabase reading' }}</p><p class="muted text-xs">Pump: <strong data-pump-status>{{ $latestReading?->pump === null ? 'No reading' : ($latestReading->pump ? 'On' : 'Off') }}</strong> · <span data-reading-freshness>{{ $latestReading && $latestReading->reading_at->gte(now()->subMinutes(config('agrisense.stale_minutes'))) ? 'Current' : 'Stale or unavailable' }}</span></p>@endif
<div class="dashboard-middle"><x-chart-card :crops="$crops" :devices="$devices" /><aside class="agri-card assistant-intro"><div class="assistant-symbol"><i data-lucide="sparkles"></i></div><span class="section-kicker">{{ __('ui.ai_assistant') }}</span><h2>{{ __('ui.evidence_starting_point') }}</h2><p>{{ __('ui.ai_photo_notice') }}</p><a href="{{ route('ai.assistant') }}" class="agri-btn agri-btn-primary">{{ __('ui.ai_assistant') }} <i data-lucide="arrow-right"></i></a></aside></div>
<div class="dashboard-bottom"><section><div class="section-heading"><div><span class="section-kicker">{{ __('ui.my_crops') }}</span><h2>{{ __('ui.my_crops') }}</h2></div><a class="text-link" href="{{ route('crops.index') }}">{{ __('ui.view_all') }} <i data-lucide="arrow-up-right"></i></a></div><div class="grid gap-5 sm:grid-cols-2">@forelse($crops->take(2) as $crop)<x-crop-card :crop="$crop" />@empty<div class="agri-card sm:col-span-2"><x-empty-state :title="__('ui.no_crops_yet')" :description="__('ui.add_first_crop')">@can('create', \App\Models\Crop::class)<a href="{{ route('crops.create') }}" class="agri-btn agri-btn-primary mt-4">{{ __('ui.add_crop') }}</a>@endcan</x-empty-state></div>@endforelse</div></section><section><div class="section-heading"><div><span class="section-kicker">{{ __('ui.field_alerts') }}</span><h2>{{ __('ui.field_alerts') }}</h2></div><a class="text-link" href="{{ route('alerts.index') }}">{{ __('ui.view_all') }}</a></div><div class="agri-card p-4 space-y-4">@forelse($alerts as $alert)<x-alert-card :alert="$alert" />@empty<x-empty-state :title="__('ui.no_active_alerts')" :description="__('ui.no_matching_alerts')" icon="bell-off" />@endforelse</div></section></div>
@endsection
