@extends('layouts.app')
@section('title',$device->name)
@section('subtitle',$device->device_id)
@section('content')
@if(auth()->user()->isAdmin() && session('device_token'))<div class="notice success"><strong>Save this token on your ESP32. It is shown only once.</strong><code class="block break-all mt-3">{{ session('device_token') }}</code></div>@endif
<div class="agri-card p-6"><div class="section-heading"><x-status-badge :status="$device->online ? 'online' : 'offline'" />@can('update', $device)<a class="agri-btn agri-btn-secondary" href="{{ route('devices.edit',$device) }}">Edit device</a>@endcan</div><p>Assigned crop: {{ $device->crop?->name ?? 'Unassigned' }}</p><p class="muted mt-2">Last contact: {{ $device->last_seen_at?->format('d M Y, H:i:s') ?? 'Never' }}</p><p class="mt-5 text-sm">Send readings over HTTPS to <code>{{ url('/api/device/readings') }}</code> with <code>Authorization: Bearer YOUR_DEVICE_TOKEN</code>.</p><a class="text-link mt-4" href="{{ route('help') }}">View ESP32 setup instructions</a>
@can('update', $device)<div class="flex flex-wrap gap-4 mt-6"><form method="POST" action="{{ route('devices.token',$device) }}" data-confirm="Replace the token? The previous token will immediately stop working.">@csrf<button class="agri-btn agri-btn-secondary">Replace device token</button></form><form method="POST" action="{{ route('devices.destroy',$device) }}" data-confirm="Disconnect this device and revoke its token?">@csrf @method('DELETE')<button class="agri-btn agri-btn-secondary">Disconnect device</button></form></div>@endcan</div>
<section class="agri-card p-6 mt-6"><h2>Recent readings</h2><div class="table-wrap mt-4"><table><thead><tr><th>Observed at</th>@foreach(config('agrisense.sensors') as $meta)<th>{{ $meta['label'] }}</th>@endforeach</tr></thead><tbody>@forelse($readings as $reading)<tr><td>{{ $reading->reading_at }}</td>@foreach(config('agrisense.sensors') as $key=>$meta)<td>{{ $reading->{$key} ?? '—' }} {{ $meta['unit'] }}</td>@endforeach</tr>@empty<tr><td colspan="6">No readings received yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
