@extends('layouts.app')
@section('title',$crop->name.' · '.$crop->variety)
@section('subtitle',$crop->scientific_name.' · '.$crop->location)
@section('content')
@if($crop->image_url && str_starts_with($crop->image_url,'crop-images/'))<div class="agri-card p-5 mb-5"><img src="{{ route('crops.image',$crop) }}" class="upload-preview" alt="{{ $crop->name }}"></div>@endif
<div class="section-heading">@if($crop->status !== 'unknown')<x-status-badge :status="$crop->status" />@endif<div class="flex flex-wrap gap-3">@can('update', $crop)<a class="agri-btn agri-btn-secondary" href="{{ route('crops.edit',$crop) }}">Edit crop</a>@endcan<a class="agri-btn agri-btn-primary" href="{{ route('ai.assistant',['crop_id'=>$crop->id]) }}"><i data-lucide="sparkles"></i>Ask AI about this crop</a></div></div>
@php($isImageIdentifiedCrop = $crop->variety === 'Unknown' && $crop->growth_stage === 'Unknown' && $crop->location === 'Unspecified')
<div class="agri-card p-5 mb-5 grid gap-4 md:grid-cols-4">@unless($isImageIdentifiedCrop)<div><span class="muted text-xs">GROWTH STAGE</span><p>{{ $crop->growth_stage }}</p></div><div><span class="muted text-xs">PLANTED</span><p>{{ $crop->planting_date }}</p></div><div><span class="muted text-xs">EXPECTED HARVEST</span><p>{{ $crop->expected_harvest_date ?? 'Not set' }}</p></div>@endunless<div><span class="muted text-xs">MONITORING DEVICES</span>@forelse($crop->devices as $device)<p><a class="text-link" href="{{ route('devices.show',$device) }}">{{ $device->name }}</a></p>@empty<p>No devices assigned</p>@can('manage-system')<a class="text-link" href="{{ route('devices.create') }}">Register a device</a>@endcan
@endforelse</div></div>
<div class="sensor-grid">@foreach(config('agrisense.sensors') as $key=>$meta)<x-sensor-card :sensor="$key" :reading="$latestReading" />@endforeach</div>
<div class="flex gap-5 mb-6"><a class="text-link" href="{{ route('monitoring.index',['crop_id'=>$crop->id]) }}">Sensor history</a><a class="text-link" href="{{ route('alerts.index',['crop_id'=>$crop->id]) }}">Crop alerts</a></div>
<section class="agri-card p-6"><h2>Verified sensor ranges</h2><p class="muted text-sm mt-2">Ranges apply to {{ $crop->variety }} at the {{ $crop->growth_stage }} stage. Record the exact page or section supporting each range.</p>
<div class="space-y-3 my-5">@forelse($crop->thresholds as $threshold)<div class="flex flex-wrap justify-between gap-3 border-b pb-3"><div><strong>{{ config('agrisense.sensors.'.$threshold->sensor_type.'.label') }}</strong> {{ $threshold->min_value ?? 'No lower limit' }} – {{ $threshold->max_value ?? 'No upper limit' }} {{ $threshold->unit }}<p class="muted text-xs">{{ $threshold->variety }} · {{ $threshold->growth_stage }} · {{ $threshold->source?->title }} · {{ $threshold->source_reference }}</p></div>@can('update', $crop)<form method="POST" action="{{ route('thresholds.destroy',[$crop,$threshold]) }}">@csrf @method('DELETE')<button class="text-link">Remove</button></form>@endcan</div>@empty<p class="muted">No verified ranges configured. Sensor readings will not be labeled healthy by default.</p>@endforelse</div>
@can('update', $crop)
@if($sources->isNotEmpty())<form method="POST" action="{{ route('thresholds.store',$crop) }}" class="grid gap-4 md:grid-cols-2">@csrf<div class="field"><label for="sensor_type">Sensor</label><select name="sensor_type" id="sensor_type">@foreach(config('agrisense.sensors') as $key=>$meta)<option value="{{ $key }}">{{ $meta['label'] }}</option>@endforeach</select></div><div class="field"><label for="source_id">Verified source</label><select name="source_id" id="source_id">@foreach($sources as $source)<option value="{{ $source->id }}">{{ $source->title }}</option>@endforeach</select></div><x-input name="min_value" label="Minimum (optional)" type="number" step="any" /><x-input name="max_value" label="Maximum (optional)" type="number" step="any" /><x-input name="source_reference" label="Supporting page / section" required /><button class="agri-btn agri-btn-primary self-end">Save range for this stage</button></form>@else<p class="notice">An administrator must verify a relevant source before ranges can be configured.</p>@endif
@endcan</section>
@can('delete', $crop)<form method="POST" action="{{ route('crops.destroy',$crop) }}" class="mt-6" data-confirm="Remove this crop? Its devices will be unassigned and crop events deleted.">@csrf @method('DELETE')<button class="text-red-700 text-sm">Delete crop</button></form>@endcan
@endsection
