@extends('layouts.app')
@section('title', __('navigation.ai_assistant'))
@section('subtitle', 'Ask practical questions about your crops and latest field conditions.')
@section('content')
<div class="assistant-layout">
<aside class="assistant-recents agri-card"><button class="agri-btn agri-btn-primary w-full" type="button" data-ai-new-chat data-endpoint="{{ route('ai.assistant.create') }}"><i data-lucide="plus"></i>New Chat</button><h2>Recents</h2><div class="assistant-recents-list">@forelse($recents as $recent)<div @class(['assistant-recent','active'=>$conversation?->id===$recent->id])><a href="{{ route('ai.assistant',['conversation'=>$recent->id]) }}"><strong>{{ $recent->title }}</strong></a><button class="assistant-recent-delete" type="button" aria-label="Delete {{ $recent->title }}" data-ai-delete-conversation data-endpoint="{{ route('ai.assistant.destroy',$recent) }}" data-current="{{ $conversation?->id===$recent->id ? 'true' : 'false' }}"><i data-lucide="ellipsis"></i></button></div>@empty<p class="muted text-sm">Your chats will appear here.</p>@endforelse</div></aside>
<section class="assistant-chat agri-card" data-ai-chat data-endpoint="{{ route('ai.assistant.chat') }}" data-clear-endpoint="{{ $conversation ? route('ai.assistant.clear',$conversation) : '' }}" data-conversation-id="{{ $conversation?->id }}" @if($crop) data-crop-id="{{ $crop->id }}" @endif>
<div class="assistant-chat-header"><div><span class="section-kicker">AGRISENSE AI</span><h2>Your field companion</h2>@if($crop)<p class="muted text-sm mt-1">Using the record and latest reading for <strong>{{ $crop->name }}</strong>@if($crop->variety) · {{ $crop->variety }}@endif.</p>@if($crop->image_url && str_starts_with($crop->image_url, 'crop-images/'))<img class="upload-preview mt-3" src="{{ route('crops.image', $crop) }}" alt="{{ $crop->name }} reference photo sent to the AI">@endif @endif</div><button class="agri-btn agri-btn-secondary" type="button" data-ai-clear><i data-lucide="trash-2"></i>Clear Chat</button></div>
<div class="assistant-chat-messages" data-ai-messages aria-live="polite" aria-label="AI Assistant conversation"></div>
<form class="assistant-chat-form" data-ai-form enctype="multipart/form-data"><label class="sr-only" for="assistant-message">Ask the AI Assistant</label><textarea id="assistant-message" name="message" rows="2" maxlength="2000" placeholder="Ask about watering, Chinese cabbage, or your sensor readings…" data-ai-input></textarea><input class="sr-only" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" data-ai-image-input><button class="agri-btn agri-btn-secondary assistant-upload-button" type="button" data-ai-upload><i data-lucide="image-up"></i><span>Upload Image</span></button><button class="agri-btn agri-btn-primary" type="submit" data-ai-send><i data-lucide="send"></i><span>Send</span></button><div class="assistant-image-preview" data-ai-image-preview hidden><img alt="Selected crop photo preview" data-ai-image-preview-image><button type="button" data-ai-remove-image aria-label="Remove selected image"><i data-lucide="x"></i></button></div></form>
<p class="muted text-sm" data-ai-status role="status"></p>
<script type="application/json" data-ai-history>@json($messages)</script>
</section>
</div>
<dialog class="assistant-delete-dialog" data-ai-delete-dialog><form method="dialog"><h2>Delete this conversation?</h2><p class="muted text-sm">This will permanently remove this chat and its uploaded images.</p><div class="form-actions"><button class="agri-btn agri-btn-secondary" value="cancel" type="submit">Cancel</button><button class="agri-btn agri-btn-primary" value="delete" type="submit">Delete</button></div></form></dialog>
@endsection
