@extends('layouts.app')
@section('title','Knowledge sources')
@section('subtitle','Manage the records stored in knowledge_base.')
@section('content')
<div class="agri-card p-6"><h2>Add knowledge-base source</h2><form method="POST" action="{{ route('admin.sources.store') }}" class="form-stack mt-5">@csrf
<x-input name="title" label="Title" :value="old('title')" required />
<div class="field"><label for="content">Content</label><textarea id="content" name="content" rows="7" maxlength="20000" required>{{ old('content') }}</textarea></div>
<x-input name="source_url" label="Source URL" type="url" :value="old('source_url')" required />
<button class="agri-btn agri-btn-primary self-start">Add source and generate embedding</button></form></div>
<div class="agri-card p-5 mt-6 table-wrap"><table><thead><tr><th>Title</th><th>Content</th><th>Source</th><th>Embedding</th><th>Created</th><th>Updated</th><th>Actions</th></tr></thead><tbody>@forelse($sources as $source)<tr><td>{{ $source->title }}</td><td>{{ \Illuminate\Support\Str::limit($source->content, 120) }}</td><td><a class="text-link" href="{{ $source->source_url }}" target="_blank" rel="noopener noreferrer">Open source</a></td><td>{{ filled($source->embedding) ? 'Ready' : 'Missing' }}</td><td>{{ $source->created_at?->toDayDateTimeString() }}</td><td>{{ $source->updated_at?->toDayDateTimeString() }}</td><td><details><summary class="text-link">Manage</summary><form method="POST" action="{{ route('admin.sources.update',$source) }}" class="form-stack mt-3">@csrf @method('PUT')<x-input name="title" label="Title" :value="$source->title" required /><div class="field"><label>Content</label><textarea name="content" rows="6" maxlength="20000" required>{{ $source->content }}</textarea></div><x-input name="source_url" label="Source URL" type="url" :value="$source->source_url" required /><button class="agri-btn agri-btn-primary">Save changes</button></form><form method="POST" action="{{ route('admin.sources.regenerate',$source) }}" class="mt-3">@csrf<button class="agri-btn agri-btn-secondary">Regenerate embedding</button></form><form method="POST" action="{{ route('admin.sources.destroy',$source) }}" class="mt-3" data-confirm="Delete this knowledge-base source?">@csrf @method('DELETE')<button class="text-red-700 text-xs">Delete source</button></form></details></td></tr>@empty<tr><td colspan="7">No knowledge-base sources yet.</td></tr>@endforelse</tbody></table>{{ $sources->links() }}</div>
@endsection
